# Generated by Django 4.2.18 on 2025-02-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0002_order_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='sub_total',
            field=models.IntegerField(),
        ),
    ]
